version: '3.9'

services:
  backend:
    build: .
    container_name: credit-risk-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data

  redis:
    image: redis:7.2-alpine
    container_name: credit-risk-redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    container_name: credit-risk-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: credit_risk
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
