"""empty message

Revision ID: 2539315e7724
Revises: 
Create Date: 2026-05-23 11:02:13.198196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2539315e7724'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_id'))

    op.drop_table('clients')
    op.drop_table('logs')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_id'))

    op.drop_table('predictions')
    op.drop_table('analytics')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_id'))

    op.drop_table('model_versions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), nullable=False),
    sa.Column('metrics', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_id'), ['id'], unique=False)

    op.create_table('analytics',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('metric_type', sa.TEXT(), nullable=True),
    sa.Column('metric_value', sa.REAL(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('input_json', sqlite.JSON(), nullable=False),
    sa.Column('prediction', sa.VARCHAR(length=32), nullable=False),
    sa.Column('probability', sa.FLOAT(), nullable=False),
    sa.Column('decision', sa.VARCHAR(length=32), nullable=False),
    sa.Column('explanation', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_id'), ['id'], unique=False)

    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=128), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=256), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=160), nullable=False),
    sa.Column('email', sa.VARCHAR(length=256), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=False),
    sa.Column('wilaya', sa.VARCHAR(length=80), nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'user'"), nullable=False),
    sa.Column('subscription_status', sa.VARCHAR(length=32), server_default=sa.text("'free'"), nullable=False),
    sa.Column('plan_tier', sa.VARCHAR(length=32), server_default=sa.text("'free'"), nullable=False),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('subscription_expires_at', sa.DATETIME(), nullable=True),
    sa.Column('monthly_predictions_used', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('predictions_month_reset', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
